# Generated by Django 4.2 on 2023-04-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='image/None/Noimage.jpg', upload_to='image'),
        ),
    ]
